/*
    SynthSound describes the kind of sound the synthesizer can play.

    In JUCE's synthesizer model, SynthesiserSound answers two questions:
    "Can this voice play this MIDI note?" and "Can this voice play this MIDI
    channel?".

    The actual audio is generated by SynthesiserVoice, not by SynthesiserSound.
    Keeping the two roles separate makes it easy for JUCE to manage polyphony:
    it can reuse one sound definition for many voices.
*/

#pragma once

#include <juce_audio_processors/juce_audio_processors.h>

namespace smolfm
{

class SynthSound final : public juce::SynthesiserSound
{
public:
    /**
        Return true because this synth can play any MIDI note.

        A more complex synth might return true only for a specific drum key or
        a particular instrument range, but for a simple synthesizer every note
        is valid.
    */
    bool appliesToNote (int /*midiNoteNumber*/) override
    {
        return true;
    }

    /**
        Return true because this synth can play on any MIDI channel.
    */
    bool appliesToChannel (int /*midiChannel*/) override
    {
        return true;
    }
};

} // namespace smolfm
